In [23]:
import numpy as np
import pandas as pd
import re

import matplotlib.pyplot as plt
%matplotlib inline

plt.rcParams["figure.figsize"] = (12,6)

# NumPy

**Задача 1**\
Сгенерировать массив из случайных положительных чисел произвольной длины. Вывести элементы, которые больше среднего арифметического.

In [68]:

array_length = np.random.randint(10, 20)
random_array = np.random.randint(1, 101, size=array_length)

mean_value = np.mean(random_array)

above_mean = random_array[random_array > mean_value]

print("Массив:", random_array)
print("Среднее арифметическое:", mean_value)
print("Элементы больше среднего:", above_mean)

Массив: [79 94 11 13 38 44 98 61 26 88 92 11 95 16]
Среднее арифметическое: 54.714285714285715
Элементы больше среднего: [79 94 98 61 88 92 95]


**Задача 2**\
Сгенерировать массив из 20 случайных элементов, элементы которого лежат в интервале [0, 10].
+ Определить количество элементов, отличающихся от минимального на 5.
+ Найти среднее арифметическое всех четных элементов массива, стоящих на нечетных местах.

In [69]:

random_array = np.random.randint(0, 11, size=20)
min_value = np.min(random_array)

count_diff_5 = np.sum(random_array == min_value + 5)

even_elements_on_odd_positions = [random_array[i] for i in range(1, len(random_array), 2) if random_array[i] % 2 == 0]

mean_even_on_odd_positions = np.mean(even_elements_on_odd_positions) if even_elements_on_odd_positions else 0

print("Массив:", random_array)
print("Минимальное значение:", min_value)
print("Количество элементов, отличающихся от минимального на 5:", count_diff_5)
print("Среднее арифметическое четных элементов на нечетных местах:", mean_even_on_odd_positions)

Массив: [3 1 2 0 7 0 2 9 8 7 1 6 9 1 8 3 8 4 1 2]
Минимальное значение: 0
Количество элементов, отличающихся от минимального на 5: 0
Среднее арифметическое четных элементов на нечетных местах: 2.4


In [70]:

random_array = np.random.randint(0, 11, size=20)
min_value = np.min(random_array)

count_diff_5 = np.sum(np.abs(random_array - min_value) > 5)

even_elements_on_odd_positions = [random_array[i] for i in range(1, len(random_array), 2) if random_array[i] % 2 == 0]

mean_even_on_odd_positions = np.mean(even_elements_on_odd_positions) if even_elements_on_odd_positions else 0

print("Сгенерированный массив:", random_array)
print("Минимальное значение:", min_value)
print("Количество элементов, отличающихся от минимального более чем на 5:", count_diff_5)
print("Среднее арифметическое четных элементов на нечетных местах:", mean_even_on_odd_positions)

Сгенерированный массив: [3 9 3 9 0 8 5 2 3 3 6 8 3 5 0 9 4 9 7 6]
Минимальное значение: 0
Количество элементов, отличающихся от минимального более чем на 5: 9
Среднее арифметическое четных элементов на нечетных местах: 6.0


**Задача 3**\
Сгенерировать матрицу A размером 5 на 5, элементы которой лежат в интервале [1, 10].
+ Возвести в квадрат максимальный элемент матрицы.
+ Все четные числа заменить на 0.

In [66]:

A = np.random.randint(1, 11, size=(5, 5))
max_value = np.max(A)

A[A == max_value] = max_value ** 2
A[A % 2 == 0] = 0

print("Матрица:")
print(A)


Матрица:
[[7 3 5 0 0]
 [0 0 0 0 0]
 [0 0 7 0 0]
 [0 3 0 0 5]
 [0 9 1 9 7]]


**Задача 4**\
Сгенерировать матрицу B размером 5 на 5, элементы которой лежат в интервале [-5, 5]. Отрицательные элементы матрицы заменить на число отрицательных элементов в строке, в которой они находятся.

In [71]:
B = np.random.randint(-5, 6, size=(5, 5))

B_mod = B.copy()

for i in range(B.shape[0]):
    negative_count = np.sum(B[i] < 0)
    B_mod[i][B[i] < 0] = negative_count

print("Исходная матрица:")
print(B)
print("\nИзменённая матрица:")
print(B_mod)

Исходная матрица:
[[ 4 -3  0  3 -2]
 [ 3 -2  5 -3 -2]
 [ 3  2 -1 -2  2]
 [-5  1 -2  1  3]
 [-3  3  3  3  3]]

Изменённая матрица:
[[4 2 0 3 2]
 [3 3 5 3 3]
 [3 2 2 2 2]
 [2 1 2 1 3]
 [1 3 3 3 3]]


# Pandas

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/rolandmueller/titanic/main/titanic3.csv")

In [55]:
# проверяем возрастные аномалии (очень большой возраст)
outlier_ages = df[df["age"] > 100]

# проверяем аномальные значения цены билета (нулевая цена или сверхвысокие значения)
outlier_fares = df[(df["fare"] == 0) | (df["fare"] > 600)]

# проверяем количество родственников (очень большое число)
outlier_sibsp_parch = df[(df["sibsp"] > 10) | (df["parch"] > 8)]

# проверяем странные значения в месте посадки
invalid_embarked = df[~df["embarked"].isin(["C", "Q", "S"])]

print("Аномальные возраста (больше 100 лет):")
print(outlier_ages, "\n")

print("Аномальные цены билетов (0 или > 600):")
print(outlier_fares, "\n")

print("Пассажиры с подозрительным числом родственников (sibsp/parch > 8):")
print(outlier_sibsp_parch, "\n")

print("Некорректные данные в порте посадки:")
print(invalid_embarked, "\n")

Аномальные возраста (больше 100 лет):
Empty DataFrame
Columns: [pclass, survived, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, boat, body, home.dest, age_group, first_name, AgeGroup]
Index: [] 

Аномальные цены билетов (0 или > 600):
      pclass  survived                                   name   sex   age  \
7          1         0                 Andrews, Mr. Thomas Jr  male  39.0   
70         1         0  Chisholm, Mr. Roderick Robert Crispin  male   NaN   
125        1         0                       Fry, Mr. Richard  male   NaN   
150        1         0                  Harrison, Mr. William  male  40.0   
170        1         1                Ismay, Mr. Joseph Bruce  male  49.0   
223        1         0          Parr, Mr. William Henry Marsh  male   NaN   
234        1         0        Reuchlin, Jonkheer. John George  male  38.0   
363        2         0                  Campbell, Mr. William  male   NaN   
384        2         0         Cunningham, Mr. Alfred Fle

In [64]:

df = df[df["age"] <= 100]

df = df[(df["fare"] > 0) & (df["fare"] <= 600)]

df = df[(df["sibsp"] <= 8) & (df["parch"] <= 8)]

df = df[df["embarked"].isin(["C", "Q", "S"])]


**Задание 1**
+ Какой была максимальная цена билета? Медиана?
+ Какова доля выживших?
+ Сколько мужчин / женщин находилось на борту?

In [65]:
#максимальная цена билета и медиана
max_fare = df["fare"].max()
median_fare = df["fare"].median()

# доля выживших
survival_rate = df["survived"].mean()

# кол-во муж/жен
gender_counts = df["sex"].value_counts()

print(f"Максимальная цена билета: {max_fare}")
print(f"Медианная цена билета: {median_fare}")
print(f"Доля выживших: {survival_rate:.2%}")
print(f"Количество мужчин: {gender_counts.get('male', 0)}")
print(f"Количество женщин: {gender_counts.get('female', 0)}")

Максимальная цена билета: 512.3292
Медианная цена билета: 15.85
Доля выживших: 40.87%
Количество мужчин: 649
Количество женщин: 386


**Задание 2**
+ Выведите распределение переменной __pclass__ для мужчин и женщин.
    + Сколько мужчин было в первом классе?
    + Сколько женщин было в третьем классе?
      
+ Создайте новый признак __age_group__, который равен:
    + 1, если пассажир был моложе 30 лет;
    + 2, если пассажиру было от 30 до 60 лет;
    + 3, если пассажир был старше 60 лет.

In [21]:
# распределение переменной pclass для мужчин и женщин
pclass_distribution = df.groupby("sex")["pclass"].value_counts()

df["age_group"] = df["age"].apply(lambda x: categorize_age(x) if pd.notnull(x) else None)

# выводим результаты
print("Распределение переменной pclass для мужчин и женщин:")
print(pclass_distribution)

Распределение переменной pclass для мужчин и женщин:
sex     pclass
female  3         216
        1         144
        2         106
male    3         493
        1         179
        2         171
Name: count, dtype: int64


In [18]:
# кол-во мужчин в первом классе
men_in_first_class = df[(df["sex"] == "male") & (df["pclass"] == 1)].shape[0]

# кол-во женщина в третьем классе
women_in_third_class = df[(df["sex"] == "female") & (df["pclass"] == 3)].shape[0]

#результаты
print(f"\nКоличество мужчин в первом классе: {men_in_first_class}")
print(f"Количество женщин в третьем классе: {women_in_third_class}")


Количество мужчин в первом классе: 179
Количество женщин в третьем классе: 216


In [20]:
#создаем новый признак age_group
def categorize_age(age):
    if age < 30:
        return 1
    elif 30 <= age <= 60:
        return 2
    else:
        return 3

# Проверяем, что новый признак создан
print("\nПример данных с новым признаком age_group:")
print(df[["age", "age_group"]].head(10))


Пример данных с новым признаком age_group:
       age  age_group
0  29.0000        1.0
1   0.9167        1.0
2   2.0000        1.0
3  30.0000        2.0
4  25.0000        1.0
5  48.0000        2.0
6  63.0000        3.0
7  39.0000        2.0
8  53.0000        2.0
9  71.0000        3.0


**Задание 3**\
Найдите самое популярное имя среди пассажиров:
+ мужчин;
+ женщин.

In [39]:

# Функция для извлечения первого имени
def extract_first_name(full_name):
    match = re.search(r'\(([^)]+)\)', full_name)  # проверяем, есть ли имя в скобках
    if match:
        return match.group(1).split()[0]  # берем первое слово из скобок (женское имя) #Если у женщицы в имени есть скобки , берем имя внутрискобок
    else:
        name_parts = full_name.split(". ")  #титул заканчивается тчкой
        if len(name_parts) > 1:
            return name_parts[1].split()[0]  # имя находится сразу после титула
    return None

# пиименяем функцию к столбцу name
df["first_name"] = df["name"].apply(extract_first_name)

# самое популярное имя среди мужчин и женщин
most_common_male_name = df[df["sex"] == "male"]["first_name"].mode()[0]
most_common_female_name = df[df["sex"] == "female"]["first_name"].mode()[0]

# Выводим результаты
print(f"Самое популярное имя среди мужчин: {most_common_male_name}")
print(f"Самое популярное имя среди женщин: {most_common_female_name}")


Самое популярное имя среди мужчин: William
Самое популярное имя среди женщин: Mary


**Задание 4**
+ Выведите данные о всех пассажирах, которые сели в Cherbourg (Embarked='C') и были старше 50 лет.
+ Выведите данные о всех женщинах младше 20 и старше 50 лет.
+ Сколько пассажиров старше 70 лет было на борту?

In [45]:
# пассажиры, которые сели в Cherbourg (Embarked='C') и были старше 50 лет
cherbourg_over_50 = df[(df["embarked"] == "C") & (df["age"] > 50)]

# Вывод результатов
print("Пассажиры, севшие в Cherbourg и старше 50 лет:")
print(cherbourg_over_50)

Пассажиры, севшие в Cherbourg и старше 50 лет:
     pclass  survived                                               name  \
9         1         0                            Artagaveytia, Mr. Ramon   
43        1         1    Bucknell, Mrs. William Robert (Emma Eliza Ward)   
48        1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)   
50        1         1  Cardeza, Mrs. James Warburton Martinez (Charlo...   
78        1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...   
104       1         1                     Eustis, Miss. Elizabeth Mussey   
123       1         1                   Frolicher-Stehli, Mr. Maxmillian   
135       1         0                          Goldschmidt, Mr. George B   
136       1         1                          Gracie, Col. Archibald IV   
174       1         0                            Kent, Mr. Edward Austin   
186       1         1          Lindstrom, Mrs. Carl Johan (Sigrid Posse)   
192       1         1                    

In [42]:
# фильтр: все женщины младше 20 и старше 50 лет
women_under_20_or_over_50 = df[(df["sex"] == "female") & ((df["age"] < 20) | (df["age"] > 50))]
#результаты
print("\nЖенщины младше 20 или старше 50 лет:")
print(women_under_20_or_over_50)


Женщины младше 20 или старше 50 лет:
      pclass  survived                                               name  \
2          1         0                       Allison, Miss. Helen Loraine   
6          1         1                  Andrews, Miss. Kornelia Theodosia   
8          1         1      Appleton, Mrs. Edward Dale (Charlotte Lamson)   
11         1         1  Astor, Mrs. John Jacob (Madeleine Talmadge Force)   
27         1         1            Bishop, Mrs. Dickinson H (Helen Walton)   
...      ...       ...                                                ...   
1265       3         0                          Van Impe, Miss. Catharina   
1273       3         0                 Vander Planke, Miss. Augusta Maria   
1279       3         0               Vestrom, Miss. Hulda Amanda Adolfina   
1300       3         1            Yasbeck, Mrs. Antoni (Selini Alexander)   
1304       3         0                               Zabour, Miss. Hileni   

         sex   age  sibsp  parch    t

In [44]:
# Кол-во пассажиров старше 70 лет
passengers_over_70 = df[df["age"] > 70].shape[0]


print(f"\nКоличество пассажиров старше 70 лет: {passengers_over_70}")


Количество пассажиров старше 70 лет: 6


**Задание 5**
+ Посчитайте средний возраст среди мужчин и среди женщин.
+ Посчитайте доли выживших в различных возрастных группах (новый признак **AgeGroup**).
+ Найдите максимальную стоимость билета в каждом из ценовых классов.

In [51]:
# средний возраст
mean_age_male = df[df["sex"] == "male"]["age"].mean()
mean_age_female = df[df["sex"] == "female"]["age"].mean()

# новый признак agegroup:
# 1 - до 18 лет, 2 - 18-40 лет, 3 - 40-60 лет, 4 - старше 60 лет
def categorize_age(age):
    if age < 30:
        return 1
    elif 30 <= age <= 60:
        return 2
    else:
        return 3
df["AgeGroup"] = df["age"].apply(lambda x: categorize_age(x) if pd.notnull(x) else None)

# Выводим результаты
print(f"Средний возраст мужчин: {mean_age_male:.2f}")
print(f"Средний возраст женщин: {mean_age_female:.2f}\n")

# доли выживших в различных возрастных группах
survival_rates_by_age_group = df.groupby("AgeGroup")["survived"].mean()

# найдем макс. стоимость билета в каждом ценовом классе (pclass)
max_fare_by_class = df.groupby("pclass")["fare"].max()

print("Доли выживших в различных возрастных группах:")
print(survival_rates_by_age_group, "\n")

print("Максимальная стоимость билета в каждом классе:")
print(max_fare_by_class)

Средний возраст мужчин: 30.59
Средний возраст женщин: 28.69

Доли выживших в различных возрастных группах:
AgeGroup
1.0    0.409490
2.0    0.418919
3.0    0.242424
Name: survived, dtype: float64 

Максимальная стоимость билета в каждом классе:
pclass
1    512.3292
2     73.5000
3     69.5500
Name: fare, dtype: float64


**Задание 6**\
Ответьте на предыдущие вопросы с помощью функции crosstab и метода pivot_table.

In [53]:

def categorize_age(age):
    if age < 30:
        return 1
    elif 30 <= age <= 60:
        return 2
    else:
        return 3

df["AgeGroup"] = df["age"].apply(lambda x: categorize_age(x) if pd.notnull(x) else None)

mean_age_pivot = df.pivot_table(values="age", index="sex", aggfunc="mean")

survival_rate_crosstab = pd.crosstab(df["AgeGroup"], df["survived"], normalize="index")

max_fare_pivot = df.pivot_table(values="fare", index="pclass", aggfunc="max")

print("Средний возраст среди мужчин и женщин (pivot_table):")
print(mean_age_pivot, "\n")

print("Доли выживших в различных возрастных группах (crosstab):")
print(survival_rate_crosstab, "\n")

print("Максимальная стоимость билета в каждом классе (pivot_table):")
print(max_fare_pivot)

Средний возраст среди мужчин и женщин (pivot_table):
              age
sex              
female  28.687071
male    30.585233 

Доли выживших в различных возрастных группах (crosstab):
survived         0         1
AgeGroup                    
1.0       0.590510  0.409490
2.0       0.581081  0.418919
3.0       0.757576  0.242424 

Максимальная стоимость билета в каждом классе (pivot_table):
            fare
pclass          
1       512.3292
2        73.5000
3        69.5500
